---
- name: "update apt packages."
  become: yes
  apt:
    update_cache: yes

# - name: "upgrade packages"
#   become: yes
#   apt:
#     upgrade: yes

- name: "install nodejs"
  become: yes
  apt:
    name: "nodejs"
    state: present
    update_cache: yes

- name: "install npm"
  become: yes
  apt:
    name: "npm"
    state: present
    update_cache: yes

- name: "install pm2"
  become: yes
  npm: 
    name: pm2
    global: yes
    state: present # https://stackoverflow.com/questions/35439934/ansible-how-to-run-node-js-application-through-pm2
#
# - name: "copy index.js file"
#   copy:
#     src: index.js
#     dest: .
#     backup: yes

# - name: "run index.js file"
#   shell: node index.js &
#  register: print_result

- name: set node to run on port 80
  become: yes
  command: setcap cap_net_bind_service=+ep /usr/bin/node

  

- name: print message
  debug:
    msg: "{{ print_result.stdout_lines }}"

